language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - mkdir -p build/logs
  - composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - composer cs-check
  - bin/phpstan analyse src/ --level=max
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - bin/php-coveralls -v --exclude-no-stmt

notifications:
    email: false
