language: php

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
        - INSTALL_PHPSTAN=no
    - php: 5.6
      env:
        - DEPS=latest
        - INSTALL_PHPSTAN=no
    - php: 7.0
      env:
        - DEPS=lowest
        - INSTALL_PHPSTAN=no
    - php: 7.0
      env:
        - DEPS=latest
        - INSTALL_PHPSTAN=no
    - php: 7.1
      env:
        - DEPS=lowest
        - INSTALL_PHPSTAN=no
    - php: 7.1
      env:
        - DEPS=latest
        - INSTALL_PHPSTAN=yes
    - php: 7.2
      env:
        - DEPS=lowest
        - INSTALL_PHPSTAN=no
    - php: 7.2
      env:
        - DEPS=latest
        - INSTALL_PHPSTAN=yes

before_script:
  - mkdir -p build/logs
  - composer self-update
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable --no-interaction ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer require http-interop/http-middleware:^0.4.1 --prefer-source --no-interaction ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer install --prefer-source --no-interaction ; fi
  - if [[ $INSTALL_PHPSTAN == 'yes' ]]; then composer require --dev phpstan/phpstan; fi
  - if [[ $INSTALL_PHPSTAN == 'yes' ]]; then composer require --dev phpstan/phpstan-webmozart-assert; fi
  - composer dump-autoload -o

script:
  - if [[ $INSTALL_PHPSTAN == 'yes' ]]; then bin/phpstan analyse src/ --level=5; fi
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bin/coveralls -v --exclude-no-stmt; fi

notifications:
    email: false
